spring.application.name=survey

# =============================================
# ?? ???? ?? (local / prod)
# =============================================
spring.profiles.active=local

# =============================================
# JPA ?? ??
# =============================================
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql

# =============================================
# JWT ?? (.env?? ??)
# =============================================
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

spring.thymeleaf.cache=false
